### ISSUE TITLE
Change vflip/hflip

### ISSUE THREAD

**Issue by markunca** [bnbe-club/rtsp-video-streamer-diy-14#1]
Hi,
any chance to have in config (or you can navigate me) how to change vflip/hflip?

Thanks

**Comment by bnbe-club** [comment]
Hi,

As mentioned in the video, this project uses the RTSP library from the following GitHub repo: https://github.com/geeksville/Micro-RTSP

Please reaise an issue there as they will be able to guide you further. 

Thanks!
